name: Upload Latest Artifacts to Release

on:
  release:
    types: [released]

jobs:
  package:
    name: Release New Slippi Nintendont
    runs-on: ubuntu-latest
    steps:
      - name: 'Get version'
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | cut -d "v" -f 2)" >> $GITHUB_ENV
      - name: Download latest artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: slippi
      - name: Zip Release Artifact
        run: |
          mv release*/apps ./
          zip -r "Slippi-Nintendont-${{ env.VERSION }}.zip" apps/
          rm -rf release* loader* apps/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
